export const CACHE_TAGS = {
	ALL: "all",
	PROJECTS: "projects",
	ABOUT: "about",
	SETTINGS: "settings",
	HERO: "hero",
} as const;

export const CACHE_DURATIONS = {
	PROJECTS: 86400,
	ABOUT: 604800,
	SETTINGS: 604800,
	HERO: 86400,
} as const;

export const CACHE_CONFIG = {
	PROJECTS: {
		TAG: CACHE_TAGS.PROJECTS,
		DURATION: CACHE_DURATIONS.PROJECTS,
	},
	ABOUT: {
		TAG: CACHE_TAGS.ABOUT,
		DURATION: CACHE_DURATIONS.ABOUT,
	},
	SETTINGS: {
		TAG: CACHE_TAGS.SETTINGS,
		DURATION: CACHE_DURATIONS.SETTINGS,
	},
	HERO: {
		TAG: CACHE_TAGS.HERO,
		DURATION: CACHE_DURATIONS.HERO,
	},
	ALL: {
		TAG: CACHE_TAGS.ALL,
		DURATION: 86400,
	},
} as const;
